DROP TABLE MANAGER.AuditTrail;
DROP TABLE MANAGER.Warnings;
DROP TABLE MANAGER.Treatments;
DROP TABLE MANAGER.Appointments;
DROP TABLE MANAGER.Available_Hours;
DROP TABLE MANAGER.Doctors;
DROP TABLE User1.Patients;
DROP TABLE User1.Rooms;

COMMIT;